I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 581, in script
    stm "Да уж! Были ведь времена, да, Димас?"
Exception: Sayer 'stm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 581, in script
    stm "Да уж! Были ведь времена, да, Димас?"
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'stm' is not defined.

Windows-10-10.0.17763
Ren'Py 7.4.2.1292
Operation Skipping School 1.0
Sun Feb 28 20:39:35 2021
